[package]
name = "simple-payment-engine"
version = "0.1.1"
edition = "2021"
authors = ["Justin Luoma <me@justin.rs>"]
license = "MIT"

[dependencies]
csv = { version = "1.3.1"}
serde = { version = "1.0.217", features = ["derive"]}
